### ISSUE TITLE
folder selection button

### ISSUE THREAD

**Issue by Arnaudv6** [err4nt/SwpieView#11] opened 2017-10-30 07:35 UTC
Hello err4nt, and thanks for this awesome soft. I adopt it from today.
I mean it : animated gif support + archive support... no open-source soft does this yet on android.

I feel awkward when entering a directory, seeing a gallery and clicking an image won't open it.
I feel the "Select" button should disapear: SwpieView would open the image you click on,
and guess the parent folder from its path.

As a side note, when pressing "back" button, all I get is a black screen.

**Comment by err4nt** [comment] 2017-11-11 20:47
Thanks for the report. I've seen the back button issue, I have a plan to fix that. Guessing the parent folder in the new android storage API is a bit of a pain but I'll see what I can come up with.

**Comment by Arnaudv6** [comment] 2017-11-18 09:15
I have no idea of the ways of Android.
But for finding the parent folder, I guess a peek at any open-source file browser (listed in f-droid for instance) will give you a working solution.

**Comment by err4nt** [comment] 2017-11-26 23:21
@Arnaudv6 Hi, both issues are fixed in the latest develop version. There seems to be some problem with the configuration for fdroid's automatic update mechanism, as soon as I get that fixed it should show up there.

**Comment by err4nt** [comment] 2017-11-27 01:56
Ok, nevermind, the fix for issue 1 worked while i was debugging, but not in normal operation. Modern android's permission system will only grant you permission to read the single file selected, not the directory it is contained in. More work required.

**Comment by Arnaudv6** [comment] 2017-11-27 08:54
Thanks for your support @err4nt.

**Comment by err4nt** [comment] 2017-11-27 15:46
Ok, the problem is the Storage Access Framework. If I use the intent to open a single file then permission is only granted for that one selected file. How about this compromise, you select a directory and get a gallery of all the images in that directory to choose from?

**Comment by Arnaudv6** [comment] 2017-11-29 12:40
Do you mean being show a gallery of thumbnails, and then choosing one file?
Then from here we could swipe left/right for previous and next images?
That for me is the ideal behaviour, and this is how most other viewer work.

**Comment by err4nt** [comment] 2017-11-29 13:47
Yes, but with the additional step of having to select a directory before you get the gallery. That is the only way to get Storage Access Framework to give you permission to read the contents of the directory, by user interaction.

**Comment by Arnaudv6** [comment] 2017-11-29 15:50
The solution you propose is ok with me.

It just feels more complicated than it needs to be though.
If it is related to Storage Access Framework, does SwpieView have to use it?
Do other viewers like [Simple-Gallery](../../../SimpleMobileTools/Simple-Gallery) have a way around then?

**Comment by err4nt** [comment] 2017-11-29 17:14
Simple-Gallery is using the media access framework, which is a problem for the use case of this application. I wanted to be able to view images from an SD card that I might have hidden from the media manager, so Simple-Gallery wouldn't see them. I'm in the middle of my work week, but I'll try to have this implemented and the fdroid repository information fixed this weekend.

**Comment by Arnaudv6** [comment] 2017-11-29 17:19
Thanks for your answer. And agreed: I too, would rather keep Storage Access Framework if it enables SD card access better. Have a nice week err4nt.

**Comment by err4nt** [comment] 2017-12-03 18:56
OK. The gallery is working. Its a little slow in this version if you have a very large directory of images. I'll work on that in subsequent versions. Also, I've bumped the version number, hopefully fdroid picks it up this time.

**Comment by Arnaudv6** [comment] 2017-12-06 15:37
I do not see the update in f-droid yet, I guess it got not picked?

**Comment by err4nt** [comment] 2017-12-06 15:39
No, it has not. The auto update mechanism is very poorly documented. I'll manually push an updated metadata file tonight

**Comment by err4nt** [comment] 2017-12-07 02:26
Ok

https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.voidptr.swpieview.txt

That updated by itself. I am hopeful that the new version should show up tonight.

**Comment by err4nt** [comment] 2017-12-16 00:26
@Arnaudv6 I am pleased to announce that SwpieView 1.3.2 finally made it up on fdroid.

**Closed as completed** 2017-12-20 00:54 UTC

**Comment by Arnaudv6** [comment] 2017-12-20 09:19
Thanks @err4nt, the update indeed showed 4 days ago. Nice.
I consider the bug closed, but I am not sure of this user experience though: feel free to keep it or reverse it at need.

Do you know of MiXplorer? I wish it was open source!
(I kept an old version, 6.14 which has better navigation through zip files).
I find its user experience better. I do not know if it is achieved by
- having one process to navigate forlders and then a second one for viewing pictures?
- using both Storage Access Framework and Media Access Framework?
